spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8082

#开启熔断的开关
feign:
  sentinel:
    enabled: true
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
